<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Reference Include="CommandSystem.Core" />
        <Reference Include="UnityEngine.UnityWebRequestModule" />
    </ItemGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        
        <Authors>Axwabo</Authors>
        <Company>Axwabo</Company>
        <Product>SecretLabNAudio.FFmpeg</Product>

        <PackageId>SecretLabNAudio.FFmpeg</PackageId>
        <PackageDescription>Advanced audio player API for SCP: Secret Laboratory using NAudio</PackageDescription>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>LGPL-3.0-only</PackageLicenseExpression>
        <PackageTags>SCP:SL LabAPI NAudio FFmpeg</PackageTags>
        <PackageProjectUrl>https://nuget.org/packages/SecretLabNAudio.FFmpeg</PackageProjectUrl>

        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/Axwabo/SecretLabNAudio</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

</Project>
