<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup>
        <Product>SecretLabNAudio.FFmpeg</Product>
        <PackageId>SecretLabNAudio.FFmpeg</PackageId>
        <PackageDescription>FFmpeg support and utilities for SecretLabNAudio</PackageDescription>
        <PackageTags>SCP:SL LabAPI NAudio FFmpeg</PackageTags>
        <PackageProjectUrl>https://nuget.org/packages/SecretLabNAudio.FFmpeg</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="SecretLabNAudio" />
    </ItemGroup>
    
    <ItemGroup>
        <Reference Include="CommandSystem.Core" />
        <Reference Include="NorthwoodLib" />
        <Reference Include="UnityEngine.UnityWebRequestModule" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

</Project>
