<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup>
        <Product>SecretLabNAudio.Core</Product>
        <PackageId>SecretLabNAudio.Core</PackageId>
        <PackageDescription>Advanced audio player API for SCP: Secret Laboratory using NAudio</PackageDescription>
        <PackageTags>SCP:SL LabAPI NAudio</PackageTags>
        <PackageProjectUrl>https://nuget.org/packages/SecretLabNAudio.Core</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

</Project>
